### ISSUE TITLE
Unit test fails

### ISSUE THREAD

**Issue by chengshiwen** [hanj4096/raftdb#3] opened 2022-01-27 10:25 UTC
Unit test fails when executing `go test -v ./...`.

If raftdb is used as a learning example, it will be better for students to fix the unit tests. While the source copy [hraftd](https://github.com/otoolep/hraftd) of raftdb is a good example

**Comment by hanj4096** [comment] 2022-02-04 04:11
The issue is fixed by 0uep.

**Closed as completed by hanj4096** 2022-02-04 04:11 UTC
